In [1]:
from duplication.main import DuplicationGenerator
import pandas as pd

In [2]:
data_name = "billionaires"
data = pd.read_csv(f"../data/{data_name}.csv")

In [3]:
generator = DuplicationGenerator()
generator.load_data(data)

In [6]:
# Create synthetic data
synthetic_data = generator.generate(feature="gender", majority="M", minority="F", n_samples=100)

In [7]:
synthetic_data

,rank,finalWorth,category,personName,age,country,city,source,industries,countryOfCitizenship,...,cpi_change_country,gdp_country,gross_tertiary_education_enrollment,gross_primary_education_enrollment_country,life_expectancy_country,tax_revenue_country_country,total_tax_rate_country,population_country,latitude_country,longitude_country
1488,1434,2100,Technology,Leonid Radvinsky,40.0,United States,NaN,E-commerce,Technology,United States,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,3.282395e+08,37.090240,-95.712891
1475,1434,2100,Food & Beverage,Daniel Lubetzky,54.0,United States,New York,Snack bars,Food & Beverage,United States,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,3.282395e+08,37.090240,-95.712891
217,215,9000,Food & Beverage,Anthony von Mandl,73.0,Canada,Vancouver,Alcoholic beverages,Food & Beverage,Canada,...,1.9,"$1,736,425,629,520",68.9,100.9,81.9,12.8,24.5,3.699198e+07,56.130366,-106.346771
533,534,5000,Finance & Investments,Ron Baron,79.0,United States,New York,Money management,Finance & Investments,United States,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,3.282395e+08,37.090240,-95.712891
469,466,5500,Technology,Patrick Collison,34.0,United States,San Francisco,Payment software,Technology,Ireland,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,3.282395e+08,37.090240,-95.712891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,97,17400,Real Estate,Donald Bren,90.0,United States,Newport Beach,Real estate,Real Estate,United States,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,3.282395e+08,37.090240,-95.712891
2314,2259,1200,Media & Entertainment,Guy Lalibert√©,63.0,Canada,Montreal,Cirque du Soleil,Media & Entertainment,Canada,...,1.9,"$1,736,425,629,520",68.9,100.9,81.9,12.8,24.5,3.699198e+07,56.130366,-106.346771
2524,2405,1100,Healthcare,Xiu Laigui,68.0,China,Tonghua,Pharmaceuticals,Healthcare,China,...,2.9,"$19,910,000,000,000",50.6,100.2,77.0,9.4,59.2,1.397715e+09,35.861660,104.195397
142,142,12200,Healthcare,Jiang Rensheng & family,69.0,China,Chongqing,Vaccines,Healthcare,China,...,2.9,"$19,910,000,000,000",50.6,100.2,77.0,9.4,59.2,1.397715e+09,35.861660,104.195397
1289,1272,2400,Media & Entertainment,Kalanithi Maran,57.0,India,Chennai,Media,Media & Entertainment,India,...,7.7,"$2,611,000,000,000",28.1,113.0,69.4,11.2,49.7,1.366418e+09,20.593684,78.962880